replicaCount: 2
image:
  repository: ghcr.io/saimudunuri04/incident-triage-agent
  tag: "d3003bbc73cac5bfcbd08d01c388d2548d5169c5"
  pullPolicy: IfNotPresent
imagePullSecrets: []
service:
  port: 8000
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 1Gi
env: {}
envFromSecretName: ""
volumeMounts: []
volumes: []
