replicaCount: 2
image:
  repository: ghcr.io/saimudunuri04/incident-triage-agent
  tag: "5c2e579c57099eca704794251300eb000a716828"
  pullPolicy: IfNotPresent
imagePullSecrets: []
service:
  port: 8000
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 1Gi
env: {}
envFromSecretName: ""
volumeMounts: []
volumes: []
