apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: incident-triage-agent
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SaiMudunuri04/incident-triage-agent.git
    targetRevision: main
    path: k8s/helm/incident-triage-agent
  destination:
    server: https://kubernetes.default.svc
    namespace: incident-triage-agent
  syncPolicy:
    automated: {prune: true, selfHeal: true}
    syncOptions: [CreateNamespace=true]
